name: Astra Cli Sample
on:
  push:
    branches:
      - main
    paths:
      - README.MD
      - '.github/workflows/cli-db-create.yml'  
jobs:
  cli-create-db:
    env:
      ASTRA_DB_APPLICATION_TOKEN: ${{ secrets.ASTRA_DB_APPLICATION_TOKEN }}
      ASTRA_DB_NAME: demo
      ASTRA_DB_KEYSPACE: demo
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Install Astra CLI
        run: curl -Ls "https://dtsx.io/get-astra-cli" | bash
        
      - name: Create DB
        run: astra db create $ASTRA_DB_NAME -k $ASTRA_DB_KEYSPACE -t $ASTRA_DB_APPLICATION_TOKEN --if-not-exists 

        
